# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2021-2023 NXP
#

MINOR_VER := 0

HSM_TEST := $(PLAT)_hsm_test
SHE_TEST := $(PLAT)_she_test
V2X_TEST := $(PLAT)_v2x_test
SHE_LIB_NAME := lib$(PLAT)_she
HSM_LIB_NAME := lib$(PLAT)_hsm
NVM_LIB_NAME := lib$(PLAT)_nvm
NVMD_CONF_FILE = nvmd_$(PLAT).conf
NVM_DAEMON = nvm_daemon_$(PLAT)
NVMD_CONFIG_SCRIPT = nvmd_$(PLAT)_conf_setup.sh

SO_EXT := so.${MAJOR_VER}.${MINOR_VER}
NVM_LIB := $(NVM_LIB_NAME).$(SO_EXT)
NVM_LIB_MAJOR := $(NVM_LIB_NAME).so.$(MAJOR_VER)
HSM_LIB := $(HSM_LIB_NAME).$(SO_EXT)
HSM_LIB_MAJOR := $(HSM_LIB_NAME).so.$(MAJOR_VER)
SHE_LIB := $(SHE_LIB_NAME).$(SO_EXT)
SHE_LIB_MAJOR := $(SHE_LIB_NAME).so.$(MAJOR_VER)

NVMD_CONFIG_SCRIPT_CP := cp $(SE_SCRIPTS_PATH)/$(NVMD_CONFIG_SCRIPT) $(DESTDIR)$(BINDIR)
INCLUDE_HEADERS_CP = cp -a include/* $(DESTDIR)$(INCLUDEDIR)
PSA := non_psa

DEFINES		+=	-DLIB_MINOR_VERSION=${MINOR_VER}\
			-DCONFIG_COMPRESSED_ECC_POINT

PLAT_OBJECTS	:=	$(PLAT_PATH)/seco_os_abs_linux.o \
			$(PLAT_PATH)/seco_utils.o \
			$(PLAT_PATH)/plat_err.o

OBJECTS	+= $(PLAT_OBJECTS)
