#!/bin/bash

if [ "0" != $# ] && [ "-l" == $1 ]
then
    find ${appdir} -name '*shx' | sort | xargs dirname | uniq
    exit -1
fi

if [ "0" != $# ] && [ "-s" == $1 ]
then
    export SETUP=1
    shift
fi

testdir=$1
appdir=`dirname $0 | xargs realpath`

if [ "0" == $# ]
then
    testdir=${appdir}/test/tests
fi

if [ ! -d ${testdir} ]
then
    echo "Usage: $0 [-s] [-l] <directory>"
    echo ""
    echo "  -s - run setup.sh / teardown.sh scripts"
    echo "  -l - list test suites (by scanning directories)"
    echo ""
    exit -1
fi

set +e

# Execute the setup.sh script, if it exists
if [ ${SETUP} ]
then
    setup=${testdir}/setup.sh

    if [ -f ${setup} ]
    then
        echo "----------------------------------------------------------------------"
        echo "Executing ${setup}"
        echo "----------------------------------------------------------------------"
        source ${setup}
    fi
fi

# Execute all of the tests  (note: ls sorts alphanumerically)
tests=`ls -1 ${testdir} | grep '.shx$'`
run_test="${appdir}/she_test"
for test in ${tests}
do
    run_test="$run_test ${test}"
done

echo "----------------------------------------------------------------------"
echo "Running testsuite ${testdir}"
echo "----------------------------------------------------------------------"
echo $run_test
echo ""
$run_test

# Execute the teardown.sh script, if it exists
if [ ${PERFORM_SETUP} ]
then
    teardown=${testdir}/teardown.sh

    if [ -f ${teardown} ]
    then
        echo "----------------------------------------------------------------------"
        echo "Executing ${teardown}"
        echo "----------------------------------------------------------------------"
        source ${teardown}
    fi
fi

