#!/bin/bash

tests=`find . -name '*shx'`

set +e

for test in ${tests}
do
    echo "---------------------------------------------------------------"
    echo ${test}
    echo "---------------------------------------------------------------"
    ./she_test ${test}
done
