# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2021-2024 NXP
#

MINOR_VER := 0

HSM_TEST := $(PLAT)_hsm_test
HSM_PERF_TEST := $(PLAT)_hsm_perf_test
TEST_PERF_CFLAGS := -DELE_PERF
SHE_TEST :=
V2X_TEST :=
SHE_LIB_NAME :=
HSM_LIB_NAME := lib$(PLAT)_hsm
NVM_LIB_NAME := lib$(PLAT)_nvm

SO_EXT := so.${MAJOR_VER}.${MINOR_VER}
NVM_LIB := $(NVM_LIB_NAME).$(SO_EXT)
NVM_LIB_MAJOR := $(NVM_LIB_NAME).so.$(MAJOR_VER)
HSM_LIB := $(HSM_LIB_NAME).$(SO_EXT)
HSM_LIB_MAJOR := $(HSM_LIB_NAME).so.$(MAJOR_VER)

EXPORT_NVM_DAEMON := cp $(NVM_DAEMON) $(DESTDIR)$(BINDIR)
EXPORT_NVMD_CONF_FILE := cp $(PLAT_COMMON_PATH)/nvm/$(NVMD_CONF_FILE) $(DESTDIR)$(ETC_DIR)
EXPORT_SYSTEMD_NVM_SERVICE := cp $(PLAT_COMMON_PATH)/nvm/$(SYSTEMD_NVM_SERVICE) $(DESTDIR)$(SYSTEMD_DIR)

INCLUDE_HEADERS_CP = cp -a include/common include/hsm include/nvm.h $(DESTDIR)$(INCLUDEDIR)
PSA := psa

DEFINES		+=	-DCONFIG_PLAT_ELE -DPLAT_ELE_FEAT_NOT_SUPPORTED=0 \
			-DLIB_MINOR_VERSION=${MINOR_VER} -DPSA_COMPLIANT \
			-DSECONDARY_API_SUPPORTED

PLAT_OBJECTS	:=	$(PLAT_PATH)/ele_os_abs_linux.o \
			$(PLAT_PATH)/ele_utils.o \
			$(PLAT_PATH)/plat_err.o

OBJECTS	+= $(PLAT_OBJECTS)
